### ISSUE TITLE
Update GH doc to explicitly state API is restricted to B2B customers

### ISSUE THREAD

**Issue by mbhynes** [pinnacleapi/apidocumentation#39]
## Problem

- The documentation for the `pinnacleapi` states that *all* customer accounts may access the endpoints, e.g.:

   - https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/GettingStarted.md
      > To get started, you would need to create an account.
         Please note that in order to access Pinnacle API, the account must be funded.

   - https://github.com/pinnacleapi/pinnacleapi-documentation
      > Please note that in order to access Pinnacle API, you must have a funded account.

- However this is not accurate; the API is now restricted to approved business-to-business customers, and when a regular funded account attempts to query the API endpoints an error response payload is returned like the following:
```
{'TIMESTAMP': '2022-06-04 20:47:53.030618',  'code': 'NO_API_ACCESS',  'message': 'Account not permitted to access the API',  'Latency': 0.167457 }
```

- If the API is now restricted, fair enough---however this documentation here is now out of date and misleading; there are several issues in this repo related to this, and the response in these to "contact the Pinnacle Solution" team is also unfortunately misleading; after contacting the B2B team the response is that:
>Thanks for your inquiry.
Due to a recent change of product offering, we don’t offer this product anymore.
We would suggest you to go to Pinnacle.com and place wagers from there.
Your understanding will be much appreciated.
  
   - (Sample issues about access):
    - https://github.com/pinnacleapi/pinnacleapi-documentation/issues/37
    - https://github.com/pinnacleapi/pinnacleapi-documentation/issues/24
    - https://github.com/pinnacleapi/pinnacleapi-documentation/issues/30

## Potential Solutions

- Update the documentation markdown files in this repo to be explicit about the restriction & criteria for which customers qualify as B2B users

### ... and FWIW, just my 0.02

The customer support team was courteous in taking the time to reply and explain that the API is now restricted to B2B customers, which is kind and much appreciated. Restricting the API is full and well in your prerogative of course, but if I may offer my 0.02 I think it would still in Pinnacle's business interest to offer a "free tier" access solution with rate limits, similar to the (pretty successful) cloud strategy of e.g. AWS, Google Cloud, etc. Allowing small customers (who could be hobbyists or side hustle startups) to work with the API allows them to build some technical debt on top of Pinnacle in whatever project they're building, and if that project is successful then that customer will need to scale up their usage, at which point they would then be in a segment of B2B customers that would pay the API fees. Shutting out all small scale "free tier" customers is a hard decision point that removes potential future customers---and since API usage is typically pareto-skewed such that the consumption by small accounts ends up being just a rounding error in your fixed platform costs compared to the variable cost of revenue that large accounts create, from the outside it would seem like you might be leaving future money on the table so-to-speak by simply restricting the API rather than considering a free tier as part of your B2B customer funnel and graduating heavy free-tier users up to more profitable segments ¯\_(ツ)_/¯

**Comment by pinnacleapi** [comment]
Thank you for taking the time to point out this inconsistency, we'll fix it shortly. Your feedback on the free tier will be passed on.

**Comment by strukiii** [comment]
Any updates here?  I also need a data feed as part of my project, and would even be willing to pay for it if made available.  Though I do intend to wager a substantial amount.  My use case seems to fall in perfectly with the 'old' ruleset -- wager enough and you can keep your access assuming it's for personal use, otherwise contact sales if you're going to resell.

**Comment by pinnacleapi** [comment]
Please contact  [pinnaclesolution.com](https://www.pinnaclesolution.com/en/contact-us) for the API access.
